### PR TITLE
Increased resolution by using an underscore.

### PR DESCRIPTION
**Pull request by AshleighAdams**

### CODE REVIEW

**Comment by niedzielski** [comment]
The underscore does not seem to align well with the baseline of the block characters.

**Comment by KateAdams** [comment]
Hmm, what font are you using?

This is how it looks to me (default Monospace in Debian on Gnome Terminal):

**Comment by niedzielski** [comment]
It looks perfect in your screenshot. It does not align well with Menlo Regular, Courier New, Monaco, Bitstream Vera Sans Mono, or Source Code Pro. It does look good in Source Sans Pro. Here's a screen shot of Menlo Regular:

screen shot 2015-03-14 at 5 59 27 pm

**Comment by niedzielski** [comment]
Maybe a more consistent alternative would be to use a space character instead of an underscore?

**Comment by KateAdams** [comment]
Above is how that looks for me.  Maybe it's best to leave it as is (no underscore/space), as those block chars are p.much guaranteed to work on any fonts.

**Comment by holman** [comment]
I think this came up awhile back as an aside in another pull request. It's too bad there's formatting differences for this, because Kate's screenshot looks prettttttty. I agree that it's likely best to hold off on this so we can keep a bit of consistency across environments, though.

**Comment by niedzielski** [comment]
Since there is opportunity for inconsistency, it'd be neat to have a command line flag to enable underscores and spaces, or even something more general, a flag to pass in all tick characters:

`spark -t' _▁▂▃▄▅▆▇█'`

(With the default being today's ticks.)

**Comment by KateAdams** [comment]
@niedzielski I would say an environment variable (`SPARK_TICKS`) would be more suitable if that were done.

**Comment by holman** [comment]
I think spark's pretty simple enough to just plug in additional characters in the local copy of it rather than supporting a flag in the repo; don't think it's necessary to add more options.

**Comment by niedzielski** [comment]
In case anyone would like to see what the changes might look like on top of @KateAdams' PR, I've made them [here](https://github.com/niedzielski/spark/tree/feature/ticks).

**Comment by KateAdams** [comment]
@niedzielski Yeah, that is much better in my opinion.

**Pull request closed without merging**
